api/urls.py
from django.urls import path

from api.views import AddMessage, GetChat, GetNotifications

urlpatterns = [
    path('response/<int:pk>/add-message/', AddMessage.as_view(), name='add_message'),
    path('response/<int:pk>/get-chat/', GetChat.as_view(), name='get_chat'),
    path('get_notifications/user/<int:pk>/', GetNotifications.as_view(), name='get_chat'),
]

cabinet_tutors/urls.py
from django.urls import path

from cabinet_tutors.views.education import EducationCreateUpdateView, EducationDeleteView
from cabinet_tutors.views.main_page_schedule import MainPageScheduleView
from cabinet_tutors.views.students_of_tutor import ToMyStudentAddView, MyStudentsView
from cabinet_tutors.views.study_formats import TutorStudyFormatsUpdateView, TutorStudyFormatsCreateView, \
    TutorStudyFormatsDeleteView
from cabinet_tutors.views.subjects_and_costs import SubjectsAndCostCreateUpdateView, SubjectsAndCostDeleteView
from cabinet_tutors.views.tutor_cabinets import TutorCabinetView, TutorCabinetUpdateView
from cabinet_tutors.views.responses import OnStudentsFromTutorView, OnTutorFromStudentResponsesView
from cabinet_tutors.views.reviews import OnMeReviewsView

urlpatterns = [
    path('<int:pk>/', TutorCabinetView.as_view(), name='tutor_cabinet'),
    path('<int:pk>/main/update', TutorCabinetUpdateView.as_view(), name='tutor_main_update'),

    path('<int:tpk>/education/create/', EducationCreateUpdateView.as_view(), name='education_create_or_update'),
    path('<int:tpk>/education/<int:pk>/delete/', EducationDeleteView.as_view(), name='education_delete'),

    path('<int:tpk>/subjects-and-costs/create-or-update/', SubjectsAndCostCreateUpdateView.as_view(),
         name='subjects_and_costs_create_or_update'),
    path('<int:tpk>/subjects-and-costs/<int:pk>/delete/', SubjectsAndCostDeleteView.as_view(),
         name='subjects_and_costs_delete'),

    path('<int:tpk>/study-formats/create/', TutorStudyFormatsCreateView.as_view(), name='tutor_study_formats_create'),
    path('<int:tpk>/study-formats/<int:pk>/update/', TutorStudyFormatsUpdateView.as_view(),
         name='tutor_study_formats_update'),
    path('<int:tpk>/study-formats/<int:pk>/delete/', TutorStudyFormatsDeleteView.as_view(),
         name='tutor_study_formats_delete'),
    path('<int:pk>/tutor-responses-on-students/', OnStudentsFromTutorView.as_view(), name='my_responses_on_students'),
    path('<int:pk>/students-responses-on-tutor/', OnTutorFromStudentResponsesView.as_view(),
         name='students_on_tutor_responses'),
    path('add_user_to_my_students/<int:pk>/', ToMyStudentAddView.as_view(),
             name='add_user_to_my_students'),
    path('<int:pk>/my_students/', MyStudentsView.as_view(),
                 name='my_students'),
    path('<int:pk>/reviews/', OnMeReviewsView.as_view(),
                     name='on_tutor_reviews'),
    path("main_tab_schedule/", MainPageScheduleView.as_view(), name="main_tab_schedule"),
]

calendarapp/urls.py
from django.urls import path

from . import views
app_name = "calendarapp"


urlpatterns = [
    path("calender/", views.CalendarViewNew.as_view(), name="calendar"),
    path("calenders/", views.CalendarView.as_view(), name="calendars"),
    path("event/new/", views.create_event, name="event_new"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path("event/<int:pk>/remove", views.EventMemberDeleteView.as_view(), name="remove_event"),
    path(
        "event/<int:pk>/delete",
        views.EventDeleteView.as_view(),
        name="event_delete",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
    path(
        "actual-event-list/",
        views.ActualEventsListView.as_view(),
        name="actual_events",
    ),
]

enimi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board_tutors_students.views.base import BoardTutorView, BoardStudentView
from enimi.views import IndexView, WorksView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('auth/', include('accounts.urls')),
                  path('', IndexView.as_view(), name='index'),
                  path('cabinet_parents/', include('cabinet_parents.urls')),
                  path('cabinet_student/', include('cabinet_student.urls')),
                  path('cabinet_tutors/', include('cabinet_tutors.urls')),
                  path('schedule/', include("calendarapp.urls")),
                  path('verification/', include('verify_email.urls')),
                  path('board_tutors_students/', include('board_tutors_students.urls')),
                  path('responses/', include("responses.urls")),
                  path('chats/', include("chat.urls")),
                  path('api/', include("api.urls")),
                  path('notifications/', include("notifications.urls")),
                  path('payments/', include("payments.urls")),
                  path('ratings/', include("ratings.urls")),
		  path('about/', WorksView.as_view(), name='about-us'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabinet_tutors/forms/study_formats.py
from django import forms

from cabinet_parents.models import OnlinePlatform
from cabinet_tutors.models import TutorStudyFormats


class TutorStudyFormatsForm(forms.ModelForm):
    online = forms.ModelMultipleChoiceField(
        label='Онлайн платформы',
        required=False,
        queryset=OnlinePlatform.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = TutorStudyFormats
        fields = ('online',)

cabinet_tutors/views/education.py
from django.urls import reverse
from django.views.generic import UpdateView, CreateView, DeleteView

from cabinet_tutors.forms.education import EducationForm, EducationFormSet
from cabinet_tutors.models import Education


class EducationCreateUpdateView(CreateView):
    template_name = 'education/education_create_or_update.html'
    form_class = EducationForm
    model = Education

    def get_context_data(self, **kwargs):
        context = super(EducationCreateUpdateView, self).get_context_data(**kwargs)
        context['formset'] = EducationFormSet(
            queryset=Education.objects.filter(tutors=self.request.user.tutor).order_by('id'))
        return context

    def post(self, request, *args, **kwargs):
        formset = EducationFormSet(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)

    def form_valid(self, formset):
        educations = formset.save(commit=False)
        for education in educations:
            education.save()
            self.request.user.tutor.education.add(education)
        return super().form_valid(formset)

    def get_success_url(self):
        return reverse('tutor_cabinet', kwargs={'pk': self.request.user.tutor.pk})


class EducationDeleteView(DeleteView):
    model = Education
    context_object_name = 'education'

    def get_success_url(self):
        return reverse('tutor_cabinet', kwargs={'pk': self.request.user.tutor.pk})

cabinet_tutors/views/main_page_schedule.py
from django.shortcuts import redirect, render
from django.utils.safestring import mark_safe
from datetime import timedelta, datetime, date
import calendar
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from calendarapp.forms import EventForm
from calendarapp.models import EventMember, Event
from calendarapp.utils import Calendar

class MainPageScheduleView(LoginRequiredMixin, ListView):
    model = Event
    template_name = "tutor_cabinet_main_page.html"
    form_class = EventForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        events = Event.objects.get_all_events(user=request.user)
        eventmembers = EventMember.objects.all()

        events_month = Event.objects.get_running_events(user=request.user)
        events_today = Event.objects.get_today_events(user=request.user)
        event_list = []
        # start: '2020-09-16T16:00:00'
        for event in events:
            event_list.append(
                {
                    "title": event.title,
                    "start": event.start_time.strftime("%Y-%m-%dT%H:%M:%S"),
                    "end": event.end_time.strftime("%Y-%m-%dT%H:%M:%S"),

                }
            )
        counter = 1
        context = {"form": forms, "events": event_list, "counter": counter,
                   "events_month": events_month, "eventmembers": eventmembers,
                   "events_today": events_today}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            form = forms.save(commit=False)
            form.user = request.user
            form.save()
            return redirect("calendarapp:calendar")
        context = {"form": forms}
        return render(request, self.template_name, context)

cabinet_tutors/views/responses.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from accounts.models import Account
from cabinet_tutors.models import TutorCabinets
from responses.models import Response


class OnStudentsFromTutorView(LoginRequiredMixin, ListView):
    template_name = 'my_responses_on_student.html'
    model = Response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OnStudentsFromTutorView, self).get_context_data(object_list=object_list, **kwargs)
        tutor_cabinet = TutorCabinets.objects.get(id=self.kwargs['pk'])
        responses = Response.objects.filter(author_id=tutor_cabinet.user.pk)
        context['responses'] = responses
        context['tutor_responses'] = '1'
        return context


class OnTutorFromStudentResponsesView(LoginRequiredMixin, ListView):
    template_name = 'on_me_from_student_responses.html'
    model = Response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OnTutorFromStudentResponsesView, self).get_context_data(object_list=object_list, **kwargs)
        tutor_cabinet = TutorCabinets.objects.get(pk=self.kwargs['pk'])
        responses = Response.objects.filter(cabinet_tutor_id=tutor_cabinet.pk)
        context['responses'] = responses
        context['student_responses'] = '1'
        return context

cabinet_tutors/views/reviews.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from accounts.models import Account
from cabinet_tutors.models import TutorCabinets
from reviews.models import Review


class OnMeReviewsView(LoginRequiredMixin, ListView):
    template_name = 'on_tutor_reviews.html'
    model = Review

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super(OnMeReviewsView, self).get_context_data(object_list=object_list, **kwargs)
        tutor_cabinet = TutorCabinets.objects.get(id=self.kwargs['pk'])

        on_tutor_reviews = Review.objects.filter(tutor_id=tutor_cabinet.user.pk)
        review_rate_list = []
        for review in on_tutor_reviews:
            review_rate_list.append(review.rate)
        if len(review_rate_list) > 0:
            middle_rate = sum(review_rate_list) / len(review_rate_list)
            context['middle_rate'] = round(middle_rate, 1)

        reviews_stats = Review.objects.filter(tutor_id=tutor_cabinet.user.pk)

        if reviews_stats:
            five_sum = []
            four_sum = []
            three_sum = []
            two_sum = []
            one_sum = []
            for rate in reviews_stats:
                if rate.rate == 5:
                    five_sum.append(rate.rate)
                if rate.rate == 4:
                    four_sum.append(rate.rate)
                if rate.rate == 3:
                    three_sum.append(rate.rate)
                if rate.rate == 2:
                    two_sum.append(rate.rate)
                if rate.rate == 1:
                    one_sum.append(rate.rate)
            five_sum = len(five_sum)
            four_sum = len(four_sum)
            three_sum = len(three_sum)
            two_sum = len(two_sum)
            one_sum = len(one_sum)
            summary_rate = five_sum + four_sum + three_sum + two_sum + one_sum
            proportion_five_sum = five_sum * 100 / summary_rate
            proportion_four_sum = four_sum * 100 / summary_rate
            proportion_three_sum = three_sum * 100 / summary_rate
            proportion_two_sum = two_sum * 100 / summary_rate
            proportion_one_sum = one_sum * 100 / summary_rate

            context['proportion_five_sum'] = round(proportion_five_sum)
            context['proportion_four_sum'] = round(proportion_four_sum)
            context['proportion_three_sum'] = round(proportion_three_sum)
            context['proportion_two_sum'] = round(proportion_two_sum)
            context['proportion_one_sum'] = round(proportion_one_sum)

            context['five_sum'] = five_sum
            context['four_sum'] = four_sum
            context['three_sum'] = three_sum
            context['two_sum'] = two_sum
            context['one_sum'] = one_sum

            context['reviews_count'] = len(review_rate_list)
        context['reviews'] = reviews_stats
        context['on_tutor_reviews'] = '1'
        return context

cabinet_tutors/views/students_of_tutor.py
from django.http import HttpResponse, JsonResponse
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

from accounts.models import Account
from cabinet_tutors.models import MyStudent, TutorCabinets
from notifications.messages import student_added_message_to_tutor, student_added_message_to_student, \
    student_added_message_to_parent


class ToMyStudentAddView(LoginRequiredMixin, CreateView):
    model = Account

    def get(self, request, *args, **kwargs):
        error = {}
        tutor = request.user
        student = Account.objects.get(id=kwargs['pk'])
        in_table = MyStudent.objects.filter(student=student, tutor=tutor)
        if not in_table:
            my_student = MyStudent.objects.create(tutor=tutor, student=student)
            student_added_message_to_tutor(tutor, student)
            if student.parent and student.with_email or not student.parent:
                student_added_message_to_student(student, tutor)
            if student.parent and not student.with_email:
                student_added_message_to_parent(student, tutor)
            return HttpResponse(status=200)
        else:
            error['error'] = 'Ученик уже в списке ваших учеников'
            return JsonResponse(error, status=400)


class MyStudentsView(LoginRequiredMixin,ListView):
    template_name = 'my_students.html'
    model = MyStudent

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MyStudentsView, self).get_context_data(object_list=object_list, **kwargs)
        tutor_cabinet = TutorCabinets.objects.get(id=self.kwargs['pk'])
        tutor = tutor_cabinet.user
        my_students = MyStudent.objects.filter(tutor_id=tutor.pk).distinct('student')
        # responses = Response.objects.filter(cabinet_tutor_id=tutor_cabinet.pk)
        # context['responses'] = responses
        context['my_students'] = my_students
        context['my_students_page'] = '1'
        return context

cabinet_tutors/views/subjects_and_costs.py
from django.urls import reverse
from django.views.generic import CreateView, DeleteView

from cabinet_tutors.forms.subjects_and_costs import SubjectsAndCostsForm, SubjectsAndCostsFormSet
from cabinet_tutors.models import SubjectsAndCosts


class SubjectsAndCostCreateUpdateView(CreateView):
    template_name = 'subjects_and_costs/subjects_and_costs_create_or_update.html'
    form_class = SubjectsAndCostsForm
    model = SubjectsAndCosts

    def get_context_data(self, **kwargs):
        context = super(SubjectsAndCostCreateUpdateView, self).get_context_data(**kwargs)
        context['formset'] = SubjectsAndCostsFormSet(
            queryset=SubjectsAndCosts.objects.filter(tutors=self.request.user.tutor).order_by('id'))
        return context

    def post(self, request, *args, **kwargs):
        formset = SubjectsAndCostsFormSet(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            context = {}
            context['errors'] = formset.errors
            context['formset'] = SubjectsAndCostsFormSet(
                queryset=SubjectsAndCosts.objects.filter(tutors=self.request.user.tutor).order_by('id'))
        return self.render_to_response(context)

    def form_valid(self, formset):
        subjects_and_costs = formset.save(commit=False)
        for subject_and_cost in subjects_and_costs:
            subject_and_cost.save()
            self.request.user.tutor.subjects_and_costs.add(subject_and_cost)
        return super().form_valid(formset)

    def get_success_url(self):
        return reverse('tutor_cabinet', kwargs={'pk': self.request.user.tutor.pk})


class SubjectsAndCostDeleteView(DeleteView):
    model = SubjectsAndCosts
    context_object_name = 'subjects_and_costs'

    def get_success_url(self):
        return reverse('tutor_cabinet', kwargs={'pk': self.request.user.tutor.pk})

cabinet_tutors/templates/tutor_about_update.html
{% extends 'base_enimi.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div class="mt-3 pb-3" style="padding-top: 75px;">
        <h5 class="text-center">О себе</h5>
        <div style="width: 480px; margin: 0 auto;">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form">
                    <div class="m-2 p-2 rounded" style="-webkit-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);
                                    -moz-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);
                                    box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);">
                        <div class="m-2">
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <div class="d-flex justify-content-between mt-3">
                        <div class="ml-2">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                        <div class="mr-1">
                            <a class="btn btn-primary mx-1" href="{% url 'tutor_cabinet' user.tutor.pk %}">Назад</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

cabinet_tutors/templates/tutor_cabinet.html
{% extends 'base_enimi.html' %}
{% load static %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="tutor__block d-flex" style="padding-top: 100px;">
            <div class="tutor__block-personal d-flex flex-column pb-3 mb-1" style="width: 25%">
                <div class="rounded text-center">
                    <p>
                        <span class="fw-bold">{{ user.last_name }}</span>
                        <span class="fw-bold">{{ user.first_name }}<br></span>
                        {% if user.father_name %}
                            <span class="fw-bold">{{ user.father_name }}<br></span>
                        {% endif %}
                    </p>
                    <img src="{{ user.avatar.url }}" alt=""
                         style="border-radius: 50%; width: 200px; height: 180px;">
                    <div>
                        <p class="pt-2">
                            <span>{{ user.email }}</span>
                            <br>
                            <span>{{ user.phone }}</span>
                        </p>
                        <p>
                            <a href="{% url 'change_password' user.pk %}">Смена пароля</a>
                        </p>
                        <div class="tut__connection_btn_block">
                            <a href="{% url 'calendarapp:calendar' %}">
                                <button class="tut__connection_btn">Расписание</button>
                            </a>
                        </div>
                    </div>
                    <div class="w-75 mt-3" style="text-align: center; background-color: #f1f9ff; border-radius: 10px; -webkit-box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2);
                                        -moz-box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2);
                                        box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2); margin-left: 35px;">
                        <div class="nav-link" aria-current="page"
                             style="padding-right: 20px">
                            <body onload="clockTimer();">
                            <div class="clockpage">
                                <span style="font-size: 25px; font-family: 'Titillium Web', sans-serif; color: #7b838a; font-weight: bold"
                                      id="clock"></span>
                                <span style="display: block;" id="dayOfWeek"></span>
                            </div>
                            </body>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tutor__info-main" style="width: 75%">

                {% if tutor.user == user %}
                    {% include 'partial/tutor_navbar.html' %}
                    {% include 'partial/tutor_info.html' %}
                    {% include 'partial/tutor_education.html' %}
                    {% include 'partial/tutor_subjects_and_costs.html' %}
                    {% include 'partial/tutor_study_formats.html' %}
                {% endif %}
            </div>

        </div>
    {% endif %}

    <script>
        function clockTimer() {
            var date = new Date();

            var time = [date.getHours(), date.getMinutes(), date.getSeconds()]; // |[0] = Hours| |[1] = Minutes| |[2] = Seconds|
            var dayOfWeek = ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"]
            var days = date.getDay();

            if (time[0] < 10) {
                time[0] = "0" + time[0];
            }
            if (time[1] < 10) {
                time[1] = "0" + time[1];
            }
            if (time[2] < 10) {
                time[2] = "0" + time[2];
            }

            var current_time = [time[0], time[1], time[2]].join(':');
            var clock = document.getElementById("clock");
            var day = document.getElementById("dayOfWeek");

            clock.innerHTML = current_time;
            day.innerHTML = dayOfWeek[days];


            setTimeout("clockTimer()", 1000);
        }
    </script>
{% endblock %}

cabinet_tutors/templates/tutor_cabinet_main_page.html
{% extends 'base_enimi.html' %}
{% load static %}
{% block extracss %}
  <link href="{% static 'calender/main.css' %}" rel="stylesheet" />
{% endblock extracss %}
{% block content %}
{% if user.is_authenticated %}
<div class="d-flex pb-3" style="padding-top: 100px;">
    <div class="d-flex flex-column" style="width: 25%">
        <div class="rounded text-center">
            <p>
                <span class="fw-bold">{{ user.last_name }}</span>
                <span class="fw-bold">{{ user.first_name }}<br></span>
                {% if user.father_name %}
                <span class="fw-bold">{{ user.father_name }}<br></span>
                {% endif %}
            </p>
            <img src="{{ user.avatar.url }}" alt=""
                 style="border-radius: 50%; width: 200px; height: 180px;">
            <div>
                <p class="pt-2">
                    <span>{{ user.email }}</span>
                    <br>
                    <span>{{ user.phone }}</span>
                </p>
                <p>
                    <a href="{% url 'change_password' user.pk %}">Смена пароля</a>
                </p>
                <div class="tut__connection_btn_block">
                    <a href="{% url 'calendarapp:calendar' %}">
                        <button class="tut__connection_btn">Расписание</button>
                    </a>
                </div>
                <div class="tut__connection_btn_block" style="margin-top: 30px">
                    <a href="{% url 'service_select' %}">
                        <button class="tut__connection_btn">Платные сервисы</button>
                    </a>
                </div>

                 <div class="w-75 mt-3" style="text-align: center; background-color: #f1f9ff; border-radius: 10px; -webkit-box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2);
                                        -moz-box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2);
                                        box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2); margin-left: 35px;">
                        <div class="nav-link" aria-current="page"
                             style="padding-right: 20px">
                            <body onload="clockTimer();">
                            <div class="clockpage">
                                <span style="font-size: 25px; font-family: 'Titillium Web', sans-serif; color: #7b838a; font-weight: bold"
                                      id="clock"></span>
                                <span style="display: block;" id="dayOfWeek"></span>
                            </div>
                            </body>
                        </div>
                    </div>

            </div>
        </div>
    </div>

    <div style="width: 75%">

        {% include 'partial/tutor_navbar.html' %}

        {% if events_today %}
        <h3 class="mb-4">Занятия сегодня:</h3>



                   <table class="table table-bordered" style="border-radius: 10px">
                      <thead>
                        <tr style="color: #737678; background-color: #c3e9f7">
                          <th scope="col">#</th>
                          <th scope="col">Занятие</th>
                          <th scope="col">Начало</th>
                          <th scope="col">Окончание</th>
                          <th scope="col">Ученики</th>
                          <th scope="col">Формат</th>
                          <th scope="col">Учеников</th>
                        </tr>
                      </thead>
                      {% for event in events_today %}
                      <tbody>

                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td><a href="{% url 'calendarapp:event-detail' event.pk %}">{{ event.title }}</a></td>
                          <td style="text-align: center">{{ event.start_time | date:"H:m"}}</td>
                          <td style="text-align: center">{{ event.end_time | date:"H:m" }}</td>
                        <td>
                          {% for member in eventmembers %}
                            {% if event.pk == member.event_id %}
                            <a href="{% url 'student_board_detail_page' member.user.survey.pk %}">
                                <i class="fa-solid fa-graduation-cap"></i> {{ member.user.last_name }}</a></span><br>
                            {% endif %}
                          {% endfor %}
                        </td>
                        <td style="text-align: center">{{ event.event_format }}</td>
                        <td style="text-align: center">{{ event.events.all|length }}</td>
                        </tr>

                      </tbody>
                      {% endfor%}
                    </table>

         {% else %}
            <p>На сегодня события не найдены</p>
         {% endif %}
    </div>


    </div>
</div>

{% endif %}

<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
crossorigin="anonymous">
</script>
 <script>
        function clockTimer() {
            var date = new Date();

            var time = [date.getHours(), date.getMinutes(), date.getSeconds()]; // |[0] = Hours| |[1] = Minutes| |[2] = Seconds|
            var dayOfWeek = ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"]
            var days = date.getDay();

            if (time[0] < 10) {
                time[0] = "0" + time[0];
            }
            if (time[1] < 10) {
                time[1] = "0" + time[1];
            }
            if (time[2] < 10) {
                time[2] = "0" + time[2];
            }

            var current_time = [time[0], time[1], time[2]].join(':');
            var clock = document.getElementById("clock");
            var day = document.getElementById("dayOfWeek");

            clock.innerHTML = current_time;
            day.innerHTML = dayOfWeek[days];


            setTimeout("clockTimer()", 1000);
        }
    </script>



  <script src="{% static 'calender/main.js' %}"></script>
  <script>
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var today = new Date();

        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialDate: today,
          navLinks: true, // can click day/week names to navigate views
          selectable: true,
          selectMirror: true,
          editable: true,
          dayMaxEvents: true, // allow "more" link when too many events
          events: {{ events|safe }},
          // events: [
          //   {
          //     title: 'All Day Event',
          //     start: '2021-06-26'
          //   },
          //   {
          //     groupId: 999,
          //     title: 'Repeating Event',
          //     start: '2020-09-16T16:00:00'
          //   },
          //   {
          //     title: 'Conference',
          //     start: '2020-09-11',
          //     end: '2020-09-13'
          //   },
          //   {
          //     title: 'Click for Google',
          //     url: 'http://google.com/',
          //     start: '2020-09-28'
          //   }
          // ]
        });

        calendar.render();
      });
      const closeBtn1 = document.getElementById('modalClose1');
      const closeBtn2 = document.getElementById('modalClose2');
      closeBtn1.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
      closeBtn2.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
  </script>
{% endblock %}