api/urls.py
from django.urls import path

from api.views import AddMessage, GetChat, GetNotifications

urlpatterns = [
    path('response/<int:pk>/add-message/', AddMessage.as_view(), name='add_message'),
    path('response/<int:pk>/get-chat/', GetChat.as_view(), name='get_chat'),
    path('get_notifications/user/<int:pk>/', GetNotifications.as_view(), name='get_chat'),
]

calendarapp/urls.py
from django.urls import path

from . import views
app_name = "calendarapp"


urlpatterns = [
    path("calender/", views.CalendarViewNew.as_view(), name="calendar"),
    path("calenders/", views.CalendarView.as_view(), name="calendars"),
    path("event/new/", views.create_event, name="event_new"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path("event/<int:pk>/remove", views.EventMemberDeleteView.as_view(), name="remove_event"),
    path(
        "event/<int:pk>/delete",
        views.EventDeleteView.as_view(),
        name="event_delete",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
    path(
        "actual-event-list/",
        views.ActualEventsListView.as_view(),
        name="actual_events",
    ),
]

enimi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board_tutors_students.views.base import BoardTutorView, BoardStudentView
from enimi.views import IndexView, WorksView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('auth/', include('accounts.urls')),
                  path('', IndexView.as_view(), name='index'),
                  path('cabinet_parents/', include('cabinet_parents.urls')),
                  path('cabinet_student/', include('cabinet_student.urls')),
                  path('cabinet_tutors/', include('cabinet_tutors.urls')),
                  path('schedule/', include("calendarapp.urls")),
                  path('verification/', include('verify_email.urls')),
                  path('board_tutors_students/', include('board_tutors_students.urls')),
                  path('responses/', include("responses.urls")),
                  path('chats/', include("chat.urls")),
                  path('api/', include("api.urls")),
                  path('notifications/', include("notifications.urls")),
                  path('payments/', include("payments.urls")),
                  path('ratings/', include("ratings.urls")),
		  path('about/', WorksView.as_view(), name='about-us'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calendarapp/models/event.py
from datetime import datetime
from django.db import models

from django.shortcuts import redirect
from django.urls import reverse

from calendarapp.models import EventAbstract
from accounts.models import Account
from calendarapp.models.event_format import EventFormat


class EventManager(models.Manager):
    """ Event manager """

    def get_all_events(self, user):
        if user.type == 'tutor':
            events = Event.objects.filter(user=user, is_active=True, is_deleted=False).order_by("start_time")

        if user.type == 'student':
            eventmembers = EventMember.objects.filter(user=user)
            events = Event.objects.filter(events__in=eventmembers)

        if user.type == 'parents':
            parent = Account.objects.get(id=user.pk)
            children = Account.objects.filter(is_deleted=False, parent_id=parent.pk).values('id', 'survey')
            children_pk_list = [child.get('id') for child in children]
            eventmembers = EventMember.objects.filter(user__in=children_pk_list)
            events = Event.objects.filter(events__in=eventmembers)

        return events

    def get_running_events(self, user):
        if user.type == 'tutor':
            running_events = Event.objects.filter(
                user=user,
                is_active=True,
                is_deleted=False,
                end_time__gte=datetime.now().date(),
            ).order_by("start_time")

        if user.type == 'student':
            eventmembers = EventMember.objects.filter(user=user)
            running_events = Event.objects.filter(
                events__in=eventmembers, is_active=True,
                is_deleted=False,
                end_time__gte=datetime.now().date(),
            ).order_by("start_time")

        if user.type == 'parents':
            children = Account.objects.filter(is_deleted=False, parent_id=user.pk).values('id', 'survey')
            children_pk_list = [child.get('id') for child in children]
            eventmembers = EventMember.objects.filter(user__in=children_pk_list)

            running_events = Event.objects.filter(
                events__in=eventmembers, is_active=True,
                is_deleted=False,
                end_time__gte=datetime.now().date(),
            ).order_by("start_time")

        return running_events

    def get_today_events(self, user):
        events_today = Event.objects.filter(
            user=user,
            is_active=True,
            is_deleted=False,
            start_time__date=datetime.now().date(),
        ).order_by("start_time")
        return events_today


class Event(EventAbstract):
    """ Event model """

    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="events")
    title = models.CharField(max_length=200, unique=False)
    description = models.TextField()
    event_format = models.ForeignKey( to='calendarapp.EventFormat',
                                      null=True,
                                      on_delete=models.CASCADE,
                                      related_name="events")
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("calendarapp:calendar")


    @property
    def get_html_url(self):
        url = reverse("calendarapp:event-detail", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'


class EventMember(EventAbstract):
    """ Event member model """

    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="events")
    user = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name="event_members"
    )

    class Meta:
        unique_together = ["event", "user"]

    def __str__(self):
        return str(self.user)

board_tutors_students/views/base.py
import datetime
from itertools import chain
from django.db.models import Q, Avg, Max, Count, Min
from django.db.models.functions import Round
from django.views.generic import ListView, DetailView
from cabinet_parents.models import Subject
from cabinet_parents.models import Survey, City
from cabinet_tutors.models import TutorCabinets, SubjectsAndCosts
from reviews.models import Review
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.core.exceptions import PermissionDenied


class BoardStudentView(LoginRequiredMixin,ListView):
    template_name = 'board_student.html'
    model = Survey
    context_object_name = 'surveys'

    def get(self, request, *args, **kwargs):
        self.min_cost = request.GET.get("min_cost")
        self.max_cost = request.GET.get("max_cost")
        self.subject = request.GET.get("subject")
        self.city = request.GET.get("city")
        self.format = request.GET.get("format")
        self.order = request.GET.get("order")
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['subjects'] = Subject.objects.all()
        context['cities'] = City.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.city and self.format == "student":
            queryset = queryset.filter(student_area__student_city__in=self.city)
        if self.city and self.format == "tutor":
            queryset = queryset.filter(tutor_area__tutor_city__in=self.city)
        if self.min_cost and self.max_cost:
            queryset = queryset.filter(
                (Q(min_cost__gte=self.min_cost) & Q(max_cost__lte=self.max_cost)) |
                (Q(min_cost__lte=self.max_cost) & Q(max_cost__gte=self.min_cost))
            )
        else:
            if self.max_cost:
                queryset = queryset.filter(Q(min_cost__lte=self.max_cost) | Q(max_cost__lte=self.max_cost))
            if self.min_cost:
                queryset = queryset.filter(Q(min_cost__gte=self.min_cost) | Q(max_cost__gte=self.min_cost))
        if self.subject:
            queryset = queryset.filter(subjects=self.subject)
        if self.order == "by_cost_up":
            queryset = queryset.order_by('min_cost', 'max_cost')
        if self.order == "by_cost_down":
            queryset = queryset.order_by('-min_cost', '-max_cost')
        return queryset

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or request.user.type == "student" or request.user.type == "parents":
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class BoardTutorView(ListView):
    template_name = 'board_tutor.html'
    model = TutorCabinets
    context_object_name = 'tutors'

    def get(self, request, *args, **kwargs):
        self.min_cost = request.GET.get("min_cost")
        self.max_cost = request.GET.get("max_cost")
        self.subject = request.GET.get("subject")
        self.city = request.GET.get("city")
        self.format = request.GET.get("format")
        self.order = request.GET.get("order")
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        query = self.get_queryset()
        print(query)
        top_tutors = TutorCabinets.objects.filter(user__services__status=1).order_by("-user__services__start_date")
        print(top_tutors)

        top_tutors = top_tutors. \
            exclude(gender=None).exclude(languages=None). \
            exclude(about=None). \
            exclude(education=None). \
            exclude(subjects_and_costs=None). \
            exclude(study_formats=None)
        if self.city and self.format == "student":
            top_tutors = top_tutors.filter(study_formats__student_area__student_city__in=self.city)
        if self.city and self.format == "tutor":
            top_tutors = top_tutors.filter(study_formats__tutor_area__tutor_city__in=self.city)
        if self.subject:
            top_tutors = TutorCabinets.objects.filter(subjects_and_costs__subject__in=self.subject)
        if self.min_cost and self.max_cost:
            subjects = SubjectsAndCosts.objects.filter(
                (Q(cost__gte=self.min_cost) & Q(cost__lte=self.max_cost)) |
                (Q(cost__lte=self.max_cost) & Q(cost__gte=self.min_cost)))
            top_tutors = TutorCabinets.objects.filter(subjects_and_costs__in=subjects)
        else:
            if self.max_cost:
                subjects = SubjectsAndCosts.objects.filter(cost__lte=self.max_cost)
                top_tutors = TutorCabinets.objects.filter(subjects_and_costs__in=subjects)
            if self.min_cost:
                subjects = SubjectsAndCosts.objects.filter(cost__gte=self.min_cost)
                top_tutors = TutorCabinets.objects.filter(subjects_and_costs__in=subjects)
        top_tutors = top_tutors.annotate(
            avg_rate=Round(Avg('user__reviews_to__rate'), 1),
            reviews_count=Count('user__reviews_to', distinct=True),
            max_experience=Max('subjects_and_costs__experience'),
            most_min_cost=(Min('subjects_and_costs__cost')),
            most_max_cost=(Max('subjects_and_costs__cost'))
        )
        if self.order == "by_cost_up":
            top_tutors = top_tutors.order_by('most_min_cost')
        if self.order == "by_cost_down":
            top_tutors = top_tutors.order_by('-most_max_cost')

        top_tutors = list(chain(top_tutors, query))
        # tutors_without_duplicates = list(set(top_tutors))
        tutors_without_duplicates = [item for i, item in enumerate(top_tutors) if item not in top_tutors[:i]]
        print(tutors_without_duplicates)

        context['top_tutors'] = tutors_without_duplicates
        context['subjects'] = Subject.objects.all()
        context['cities'] = City.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by("-user__created_at").exclude(user__services__status=1)
        # queryset = super().get_queryset().order_by("user__services__status", "-user__services__start_date")
        queryset = queryset. \
            exclude(gender=None).exclude(languages=None). \
            exclude(about=None). \
            exclude(education=None). \
            exclude(subjects_and_costs=None). \
            exclude(study_formats=None)
        if self.city and self.format == "student":
            queryset = queryset.filter(study_formats__student_area__student_city__in=self.city)
        if self.city and self.format == "tutor":
            queryset = queryset.filter(study_formats__tutor_area__tutor_city__in=self.city)
        if self.subject:
            queryset = TutorCabinets.objects.filter(subjects_and_costs__subject__in=self.subject)
        if self.min_cost and self.max_cost:
            subjects = SubjectsAndCosts.objects.filter(
                (Q(cost__gte=self.min_cost) & Q(cost__lte=self.max_cost)) |
                (Q(cost__lte=self.max_cost) & Q(cost__gte=self.min_cost)))
            queryset = TutorCabinets.objects.filter(subjects_and_costs__in=subjects)
        else:
            if self.max_cost:
                subjects = SubjectsAndCosts.objects.filter(cost__lte=self.max_cost)
                queryset = TutorCabinets.objects.filter(subjects_and_costs__in=subjects)
            if self.min_cost:
                subjects = SubjectsAndCosts.objects.filter(cost__gte=self.min_cost)
                queryset = TutorCabinets.objects.filter(subjects_and_costs__in=subjects)
        queryset = queryset.annotate(
            avg_rate=Round(Avg('user__reviews_to__rate'), 1),
            reviews_count=Count('user__reviews_to', distinct=True),
            max_experience=Max('subjects_and_costs__experience'),
            most_min_cost=(Min('subjects_and_costs__cost')),
            most_max_cost=(Max('subjects_and_costs__cost'))
        )
        if self.order == "by_cost_up":
            queryset = queryset.order_by('most_min_cost')
        if self.order == "by_cost_down":
            queryset = queryset.order_by('-most_max_cost')
        return queryset




class TutorBoardDetailPageView(DetailView):
    template_name = 'tutor_board_detail_page.html'
    model = TutorCabinets
    context_object_name = 'tutor'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tutor = TutorCabinets.objects.get(id=self.object.pk)
        on_tutor_reviews = Review.objects.filter(tutor=tutor.user)
        review_rate_list = []
        for review in on_tutor_reviews:
            review_rate_list.append(review.rate)
        if len(review_rate_list) > 0:
            middle_rate = sum(review_rate_list) / len(review_rate_list)
            context['middle_rate'] = round(middle_rate, 1)

        cost_list = []
        costs = SubjectsAndCosts.objects.filter(tutors=self.object)
        exp = SubjectsAndCosts.objects.filter(tutors=self.object).order_by('-experience').first()
        print(exp)
        experience = exp.experience
        for cost in costs:
            cost_list.append(cost.cost)
        if len(cost_list) > 0:
            middle_cost = round(sum(cost_list) / len(cost_list))
            context['middle_cost'] = middle_cost
        educations = tutor.education.all()

        reviews = Review.objects.filter(tutor_id=tutor.user.pk)

        reviews_stats = Review.objects.filter(tutor_id=tutor.user.pk)
        if reviews_stats:
            five_sum = []
            four_sum = []
            three_sum = []
            two_sum = []
            one_sum = []
            for rate in reviews_stats:
                if rate.rate == 5:
                    five_sum.append(rate.rate)
                if rate.rate == 4:

enimi/accounts/views/base.py
from accounts.models.accounts import UserCategoryChoices
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['types'] = UserCategoryChoices.choices
        return context

templates/add_member.html
{% extends 'base_enimi.html' %}
{% load django_bootstrap5 %}
{% block title %}
Добавить участника
{% endblock %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

    {% if error %}

    <div class="content" style="background-color: white; border-radius: 10px; margin: 0 auto; padding: 65px; margin-top:-30px; margin-bottom: 60px; width: 55%; -webkit-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);">

        <h3 style="text-align: center">{{ error }}</h3>
        <div class="row">
            <div class="col-12 text-center">
                <a style="text-align: center" href="{% url 'calendarapp:calendar' %}">
                    <button id="btn-back-to-board" type="button" class="btn btn-primary"style="margin-top: 20px">Закрыть</button>
                 </a>
            </div>
        </div>


    </div>

    {% elif ok %}

    <div class="content" style="background-color: white; border-radius: 10px; margin: 0 auto; padding: 65px; margin-top:-30px; margin-bottom: 60px; width: 55%; -webkit-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);">

        <h3 style="text-align: center">{{ ok }}</h3>
        <div class="row">
            <div class="col-12 text-center">
                <a style="text-align: center" href="{% url 'calendarapp:calendar' %}">
                    <button id="btn-back-to-board" type="button" class="btn btn-primary"style="margin-top: 20px">Закрыть</button>
                 </a>
            </div>
        </div>


    </div>

    {% else %}

        <div class="content" style="background-color: white; border-radius: 10px; margin: 0 auto; padding: 65px; margin-top:-30px; width: 50%; -webkit-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);
                -moz-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);
                box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);">
                    <h2 style="margin: 20px auto; text-align:center; ">Добавление участника</h2><div>
                        <form action="" method="POST" enctype="multipart/form-data">
                         {% csrf_token %}
                            <div class="form" >
                                {% bootstrap_form form %}
                                <div class="row">
                                    <div class="col-6 text-center">
                                            <button type="submit" class="btn btn-primary btn-block">Сохранить</button>
                                   </div>
                                   <div class="col-6 text-right">
                                      <a href="{% url 'calendarapp:calendar' %}">
                                        <button type="button" class="btn btn-primary">Отмена</button>
                                       </a>
                                   </div>



                                </div>
                            </div>
                        </form>
                    </div>
                </div>

{% endif %}
{% endblock %}

templates/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

templates/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
    <span class="left m-2" style="font-size: 20px;">Добро пожаловать, {{ request.user }}</span>
    <a class="btn btn-info right" href="{% url 'accounts:signout' %}"> Sign Out</a>
	<a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ next_month }} "> Следующий месяц >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Предыдущий месяц </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_new' %}"> + Новое событие </a>
</div>
<div style="color: blueviolet;">
    {{ calendar }}
</div>
{% endblock %}

templates/event-details.html
{% extends 'base_enimi.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
Подробности занятия
{% endblock %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="content" style="background-color: white; border-radius: 10px; margin: 0 auto; padding: 35px; margin-top:-30px; width: 100%; -webkit-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);
        -moz-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);
        box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);">
        <h2 style="margin: 20px auto; text-align:center; ">Описание занятия</h2><div>
        {% if request.user.type == 'tutor' %}
            <hr>
            <div class="row justify-content-center">
                <div class="col-4">
                    <p>Название события:</p><h4> {{ event.title }}</h4>
                </div>
                <div class="col-4">
                    <p>Начало: <span style="color: gray;"><h4>{{ event.start_time }}</h4></span>
                </div>
                <div class="col-4">
                    <p>Конец <span style="color: gray;"><h4>{{ event.end_time }}</h4></span></p>
                </div>
            </div>

            <p>Подробности:</p><h4>{{ event.description }}</h4>
        <hr>
        {% endif %}
        {% if request.user.type != 'tutor' %}
        <div class="row justify-content-center" style="margin-top: 40px">
            <div class="col-6">
                <div class="clearfix">
                    <p>Название события:</p><h4> {{ event.title }}</h4>
                    <p>Начало: <span style="color: gray;"><h4>{{ event.start_time }}</h4></span>
                    <p>Конец <span style="color: gray;"><h4>{{ event.end_time }}</h4></span></p>
                    <p>Подробности:</p><h4>{{ event.description }}</h4>
                </div>
            </div>

            <div class="col-6">
                <p>Преподаватель:</p><h4>{{ event.user.first_name }} {{event.user.last_name }}</h4>
                <p>Телефон:</p><h4>{{ event.user.phone }}</h4>
                <p>email:</p><h4>{{ event.user.email }}</h4>
            </div>
            <hr>
        </div>
        {% endif %}



    {% if request.user.type == 'tutor' %}

        <div class="clearfix">

            <h3 class="left" style="margin-top: 30px; margin-bottom: 30px; text-align: center" > Ученики</h3>
        </div>
    </div>
        <table class="table table-bordered">
            <thead>
                <tr style="color: #737678; background-color: #c3e9f7">
                  <th style="width: 10px">#</th>
                  <th>Имя</th>
                  <th>Телефон</th>
                  <th>Email</th>
                  <th>Формат</th>
                  <th>Оценка</th>
                  {% if request.user.type == 'tutor' %}
                  <th>#</th>
                  <th>#</th>
                  {% endif %}
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'student_board_detail_page' member.user.survey.pk %}">{{ member.user.first_name }} {{ member.user.last_name }}</a></td>
                    <td>{{ member.user.phone }}</td>
                    {% if event.user.with_email == False %}
                        <td>{{ member.user.email }}</td>
                    {% else %}
                        <td>{{ member.user.email }}</td>
                    {% endif %}
                    <td data-id="{{ event.pk }}" id="{{ event.pk }}">{{ event.event_format }}</td>

                    <td style="text-align: center;" data-id="{{ member.pk }}" id="member_{{ member.pk }}">
                        {% for rate in event_member_ratings %}
                            {% if member.pk == rate.event_member.pk %}
                                {{ rate.score }}
                            {% endif %}
                      {% endfor %}
                    </td>

                    {% if request.user.type == 'tutor' %}

                        <td>
                            <button class="btn btn-success" type="button" id=""
                                    data-event_id="{{ event.pk }}" data-member_id="{{ member.pk }}">Оценить
                            </button>
                        </td>

                        <td>
                            <a class="btn btn-danger" href="{% url 'calendarapp:remove_event' member.id %}">Удалить ученика</a>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
              </tbody>
        </table>



            <div class="row justify-content-between" style="margin-top: 40px">
                <div class="col-4">
                    <a class="btn btn-primary right" href="{% url 'calendarapp:add_eventmember' event.id %}"> Добавить участника </a>
                </div>
                <div class="col-4 text-center">
                    <a class="btn btn-primary left" href="{% url 'calendarapp:calendar' %}"> Расписание </a>
                </div>
                <div class="col-4 text-right">
                    <a class="btn btn-primary right mr-2" href="{% url 'calendarapp:event_edit' event.pk %}"> Редактировать событие </a>

                </div>
                <div style="margin-top: 30px">
                    <a href="{{ back_page }}">
                        <button class="tut__connection_btn">Назад</button>
                    </a>
                </div>
            </div>
        {% else %}
            <a href="{{ back_page }}">
                <button class="tut__connection_btn">Назад</button>
            </a>


        {% endif %}
        </div>


    <div id="rateCreateModal" class="modal"
         style="display: none; width: 100%; height: 100%; border-radius: 30px; z-index: 1; overflow: auto">
        <div class="modal-content"
             style="background-color: white; margin: 10% auto; border-radius: 15px; padding: 20px; width: 30%; -webkit-box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2);
                                    -moz-box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2);
                                    box-shadow: 0px 0px 8px 4px rgba(34, 60, 80, 0.2);">
            <h2 style="margin: 20px auto; text-align:center; ">Оцените ученика</h2>
                <form action="" method="POST" enctype="multipart/form-data">
                 {% csrf_token %}
                    <div class="form" >
                        {% bootstrap_form rate_form %}
                        <div class="row justify-content-between">
                            <div class="col-6 text-center">
                                 <button type="button" id="btnRateCreate" data-event_id="" data-member_id="" class="btn btn-primary">Оценить</button>
                            </div>

                            <div class="col-6 text-center">
                                 <button id="btnClose" data-event_id="" data-member_id="" class="btn btn-success">Отмена</button>
                            </div>
                        </div>

                    </div>
                </form>

        </div>
    </div>

    <div class="container">

    </div>

<script src="{% static 'js/event_members_rates.js' %}"></script>

{% endblock %}

templates/event.html
{% extends 'base_enimi.html' %}
{% load django_bootstrap5 %}
{% block title %}Событие
{% endblock %}

{% block content %}
<br>
<br>
<br>
<br>
<br>

<div class="content" style="background-color: white; border-radius: 10px; margin: 0 auto; padding: 65px; margin-top:-30px; width: 50%; -webkit-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);
        -moz-box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);
        box-shadow: -1px 1px 14px 5px rgba(34, 60, 80, 0.16);">
            <h2 style="margin: 20px auto; text-align:center; ">Редактирование события</h2><div>
                <form action="" method="POST" enctype="multipart/form-data">
                 {% csrf_token %}
                    <div class="form" >
                        {% bootstrap_form form %}
                        <div class="row">
                            <div class="col-6 text-center">
                                    <button type="submit" class="btn btn-primary btn-block">Сохранить</button>
                           </div>
                           <div class="col-6 text-right">
                              <a href="{% url 'calendarapp:calendar' %}">
                                <button type="button" class="btn btn-primary">Отмена</button>
                               </a>
                           </div>



                        </div>
                    </div>
                </form>
            </div>
        </div>

{% endblock %}